#!/bin/bash

# The input file containing the lines you want to check
input_file="$1"

# Check for a provided file
if [[ -z "$input_file" ]]; then
  echo "Please provide an input file."
  exit 1
fi

# The regex pattern
# The (?i) is for case-insensitive matching
# The \s* at the end is for optional trailing whitespace
pattern='^(?i)(ref|refs|reference|references|res|resolve|resolves|resolved|close|closes|closed|fix|fixes|fixed)\s*:\s*((#|gh-)\d+|[A-Za-z]+-\d+)\s*$'

# Scan the entire file for lines matching the pattern
if grep -Pq "$pattern" "$input_file"; then
  echo """
  Commit message meets requirements.
  """
  exit 0
else
  echo """
  Commit message does not meet the requirements.

  If commit resolves an issue or ticket, amend the commit to
  include a reference to the issue or ticket like so:
  
  resolves: PROJ-1234
  or
  resolves: #123 (if resolving a GitHub issue)

  If commit does not resolve an issue or ticket, but was
  done while working on an issue, amend the commit to include
  a reference to the issue or ticket like so:

  reference: PROJ-1234
  or
  reference: #123 (if referencing a GitHub issue)

  Don't have a ticket to reference? You should create one.
  """
  exit 1
fi
